[package]
name = "cgt_py_widgets"
version = "0.10.0"
edition = "2024"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "../README.md"
repository = "https://github.com/t4ccer/cgt-tools"
homepage = "https://cgt-tools.tools"
keywords = ["cgt"]
categories = ["mathematics", "science"]
publish = false
description = "Jupyter widget frontend for the `cgt` Python bindings"

[lib]
name = "cgt_py_widgets"
crate-type = ["cdylib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
web-sys.workspace = true
wasm-bindgen.workspace = true
cgt_py_messages = { path = "../cgt_py_messages" }
cgt = { path = "../.", features = ["serde"] }
jupyter_rust_widget_frontend = { path = "../jupyter_rust_widget_frontend" }
wasm-bindgen-futures = { version = "0.4.77", default-features = false }
futures-signals = { version = "0.3.34", default-features = false }
