guides = ["guides/python-installation.md", "guides/custom-widgets.ipynb"]

[play.quelhas]
easy = { path = "./checkpoints/quelhas_easy.bin" }

[play.fjords]
easy = { path = "./checkpoints/fjords_easy.bin" }
