[package]
name = "cgt_py"
version = "0.10.0"
edition = "2024"
authors = ["Tomasz Maciosowski <t4ccer@gmail.com>"]
license = "AGPL-3.0"
readme = "../README.md"
repository = "https://github.com/t4ccer/cgt-tools"
description = "Python bindings for Rust `cgt` package"
homepage = "https://github.com/t4ccer/cgt-tools"
keywords = ["cgt"]
categories = ["mathematics", "science"]

[lib]
name = "cgt_py"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cgt_py_stub_gen"
path = "src/bin/stub_gen.rs"

[dependencies]
pyo3 = { workspace = true }
pyo3-stub-gen = { workspace = true }
cgt = { path = "../.", features = ["serde"] }
cgt_py_messages = { path = "../cgt_py_messages" }
jupyter_rust_widget_backend = { path = "../jupyter_rust_widget_backend" }
